version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            - npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build docker image
          command: |
            - docker build -t circleci_nodejs_app -t robinthakur00/circleci_nodejs_app:latest .
            - echo $DOCKER_PASSWORD | docker login -u robinthakur00 --password-stdin
            - docker push robinthakur00/circleci_nodejs_app:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image

  